### ISSUE TITLE
claude-3-5-sonnet-20240620

### ISSUE THREAD

**Issue by Root-FTW** [ziyanwould/AIForAl#1]
Could you add the new Anthropic model?

I would like you to add the model: claude-3-5-sonnet-20240620

---

您能添加新的人类学模型吗？

我希望您添加模型：Claude-3-5-sonnet-20240620

**Comment by ziyanwould** [comment]
Added successfully. Welcome to use.
已添加完成，欢迎使用

**Comment by ziyanwould** [comment]
close

**Comment by Root-FTW** [comment]
I cannot use it 

---

我不能使用它

---

![Captura de pantalla 2024-07-02 092554](https://github.com/ziyanwould/AIForAl/assets/108767514/d9b86f15-567c-47a0-bfb5-3f707f4bed28)


![Captura de pantalla 2024-07-02 092717](https://github.com/ziyanwould/AIForAl/assets/108767514/c5a54d32-79f1-4ad5-b1d2-cdd66dc5613d)

![Captura de pantalla 2024-07-02 092726](https://github.com/ziyanwould/AIForAl/assets/108767514/c9da26af-334f-4217-904f-3e017d12454d)

**Comment by Root-FTW** [comment]
Hi [ziyanwould](https://github.com/ziyanwould)

What is the website where I can use your claude-3-5-sonnet-20240620?

I tried this website: https://robot.liujiarong.top/, and claude-3-5-sonnet-20240620 does not work.

Is it a different site where https://robot.liujiarong.top/ works?


---


哪个网站可以使用您的 claude-3-5-sonnet-20240620？

我试过这个网站：https://robot.liujiarong.top/，但 claude-3-5-sonnet-20240620 无法使用。

https://robot.liujiarong.top/ 是另一个可以使用的网站吗？

**Comment by ziyanwould** [comment]
https://chatnio.liujiarong.top
<img width="1827" alt="截屏2024-07-06 08 50 23" src="https://github.com/ziyanwould/AIForAl/assets/22288807/54e03912-d494-445f-9eca-35306f989951">

**Comment by ziyanwould** [comment]
是的需要到另外一个网站注册登录才能使用

**Comment by ziyanwould** [comment]
你有秘钥，也可以增加进去，就可以直接使用

**Comment by Root-FTW** [comment]
I thought it was free like GPT4o, I didn't think it would cost anything to use it

---

我以为它和 GPT4o 一样是免费的，没想到使用它不需要任何费用

**Comment by ziyanwould** [comment]
官网免费使用。目前没有找到适合的免费源，因此没办法免费提供。
