### ISSUE TITLE
你好API可以分享一下吗

### ISSUE THREAD

**Issue by Xmf111** [ziyanwould/AIForAl#2]
求API获取途径，留给v私聊您

**Comment by ziyanwould** [comment]
你说的哪些模型呢？

**Comment by Xmf111** [comment]
> 你说的哪些模型呢？

国内可以用的Claude，lama70，gemini。我好像都没有🥺

**Comment by ziyanwould** [comment]
![IMG_1391](https://github.com/ziyanwould/AIForAl/assets/22288807/69d2ea97-15f4-4d87-9a14-0f4f79add191)

**Comment by ziyanwould** [comment]
已留下联系方式~
