### ISSUE TITLE
你好，我正在尝试在网站 https://robot.liujiarong.top/ 上使用 01-Mini 和 01-Preview 模型。

### ISSUE THREAD

**Issue by Root-FTW** [ziyanwould/AIForAl#3]
你好，我正在尝试在网站 https://robot.liujiarong.top/ 上使用 01-Mini 和 01-Preview 模型。

但我遇到了以下错误：

{
  "error": {
    "name": "TypeError",
    "stack": "TypeError: Cannot read properties of undefined (reading 'map')\n    at Object.start (/app/.next/server/edge-chunks/210.js:9:2001)\n    at setupReadableStreamDefaultController (node:internal/webstreams/readablestream:2455:23)\n    at setupReadableStreamDefaultControllerFromSource (node:internal/webstreams/readablestream:2487:3)\n    at new ReadableStream (node:internal/webstreams/readablestream:280:7)\n    at B (/app/.next/server/edge-chunks/210.js:9:1947)\n    at Object.chat (/app/.next/server/edge-chunks/210.js:9:3535)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async /app/.next/server/app/api/chat/openai/route.js:1:1667\n    at async /app/.next/server/edge-chunks/490.js:1:90730\n    at async $.execute (/app/.next/server/edge-chunks/490.js:1:88440)",
    "message": "Cannot read properties of undefined (reading 'map')"
  },
  "endpoint": "http://192.168.***.135:****/v1",
  "provider": "openai"
}
你能帮我修复这个问题吗？我非常喜欢 https://robot.liujiarong.top/ 这个平台，能够在这个平台上使用这些模型会很棒。

我知道我可以在 https://chatnio.liujiarong.top/ 上使用它们，但我不太喜欢那个平台；我更喜欢 https://robot.liujiarong.top/ 这个平台。

-----

Hello, I am trying to use the 01-Mini and 01-Preview models on the website:
https://robot.liujiarong.top/

However, I am encountering the following error:

{
  "error": {
    "name": "TypeError",
    "stack": "TypeError: Cannot read properties of undefined (reading 'map')\n    at Object.start (/app/.next/server/edge-chunks/210.js:9:2001)\n    at setupReadableStreamDefaultController (node:internal/webstreams/readablestream:2455:23)\n    at setupReadableStreamDefaultControllerFromSource (node:internal/webstreams/readablestream:2487:3)\n    at new ReadableStream (node:internal/webstreams/readablestream:280:7)\n    at B (/app/.next/server/edge-chunks/210.js:9:1947)\n    at Object.chat (/app/.next/server/edge-chunks/210.js:9:3535)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async /app/.next/server/app/api/chat/openai/route.js:1:1667\n    at async /app/.next/server/edge-chunks/490.js:1:90730\n    at async $.execute (/app/.next/server/edge-chunks/490.js:1:88440)",
    "message": "Cannot read properties of undefined (reading 'map')"
  },
  "endpoint": "http://192.168.***.135:****/v1",
  "provider": "openai"
}
Could you help me fix this? I really like the platform at https://robot.liujiarong.top/ and it would be great to be able to use those models there.

I know I can use them at https://chatnio.liujiarong.top/, but I don’t like that one as much; I prefer the platform at https://robot.liujiarong.top/.

**Comment by ziyanwould** [comment]
已修复

**Comment by ziyanwould** [comment]
关闭
